version: "3.6"

services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    networks:
      - nas

  backend:
    build: ./
    links:
      - db
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://postgres@db
      RAILS_MAIN_DB: indahouse_nas_dghTmmjy6LPhV4lkNTwF
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - nas

  nginx:
    build: ./nginx
    depends_on:
      - backend
    ports:
      - 8000:80
    networks:
      - nas

networks:
  nas:
    driver: bridge
